### ISSUE TITLE
Won't render guid with isPermaLink=false

### ISSUE THREAD

**Issue by TiGR** [suin/php-rss-writer#11]
As per [specs](http://cyber.law.harvard.edu/rss/rss.html#ltguidgtSubelementOfLtitemgt):

> isPermaLink is optional, its _default value is true_. If its value is false, the guid may not be assumed to be a url, or a url to anything in particular.

But current code does not allow rendering `guid` with `isPermaLink="false"`. It would silently drop isPermaLink if it is equal to false.

**Comment by barryp** [comment]
Yes, I'm getting burned by this too
