### ISSUE TITLE
Allowing CDATA elements as needed?

### ISSUE THREAD

**Issue by jrumbut** [suin/php-rss-writer#16]
Hi there!

Really love the library, particularly the intuitive interface, however my RSS feeds require use of CDATA wrapped HTML content.

I'm going to be forking the library and implementing it myself, I wonder if you would be interested in a pull request to support this functionality?

**Comment by zcuric** [comment]
👍 on this.

**Comment by suin** [comment]
CDATA is now available from [version 1.5.0](https://github.com/suin/php-rss-writer/releases/tag/1.5.0)!

**Comment by jrumbut** [comment]
This looks really good, perfect timing too!
