### ISSUE TITLE
Call to undefined method Suin\RSSWriter\Channel::feedUrl()

### ISSUE THREAD

**Issue by sessionstop** [suin/php-rss-writer#22]
Hi, 

Thanks for writing this great tool. When I use it, it throws an error.

Fatal error: Uncaught Error: Call to undefined method Suin\RSSWriter\Channel::feedUrl()

Any ideas? I tried 1.5.0 and 1.4.0, with no luck.

**Comment by suin** [comment]
I have forgotten to release new version which has feedUrl. Now I have released it as 1.6.0. Could you check out the version? Thank you.

**Comment by sessionstop** [comment]
It's ok now! Thanks!
