### ISSUE TITLE
Picture to post

### ISSUE THREAD

**Issue by PoTHuYJoHN** [suin/php-rss-writer#7]
Is it possible to add picture to post?

**Comment by brettalton** [comment]
Use $item->enclosure('http://example.com/example.jpg', '234323432', 'image/jpg');

More on the RSS enclosure spec: https://www.wikiwand.com/en/RSS_enclosure

**Comment by jaspal747** [comment]
Please add this to the example or the readme doc. Will be super helpful!
Thanks
